import type {
  CategoryInput,
  LevelInput,
  QuoteInput,
  RewardInput,
  RuleInput,
  SettingsInput,
} from "@shared/contracts";

export const DEFAULT_SETTINGS: SettingsInput = {
  appName: "猪梨成长计划 ❤️",
  subtitle: "每一点努力，都值得被认真记录。",
  pigName: "猪猪",
  pearName: "梨梨",
  heroTitle: "把认真生活的每一刻，都变成看得见的成长",
  heroDescription:
    "做饭、陪伴、克制熬夜、准备惊喜，每一点温柔努力都值得被认真记下来。",
  welcomeTitle: "今天也在一起长大",
  welcomeDescription:
    "这里只有猪猪和梨梨的日常宇宙。积分会流动，成长值会积累，奖励会慢慢解锁。",
  timezone: "Asia/Shanghai",
};

export const DEFAULT_CATEGORIES: CategoryInput[] = [
  {
    name: "家务",
    slug: "home-care",
    description: "认真照顾小家的一切。",
    accentColor: "#f6b2bf",
    icon: "🍳",
    sortOrder: 1,
    isActive: true,
  },
  {
    name: "陪伴",
    slug: "companionship",
    description: "温柔陪伴和一起生活的时刻。",
    accentColor: "#f3cf8f",
    icon: "🌷",
    sortOrder: 2,
    isActive: true,
  },
  {
    name: "习惯",
    slug: "habit",
    description: "让生活慢慢变好的小习惯。",
    accentColor: "#a6d1bc",
    icon: "🫧",
    sortOrder: 3,
    isActive: true,
  },
  {
    name: "惊喜",
    slug: "surprise",
    description: "让人心动的小小加分项。",
    accentColor: "#ffbfce",
    icon: "🎀",
    sortOrder: 4,
    isActive: true,
  },
];

export const DEFAULT_RULES: RuleInput[] = [
  {
    kind: "positive",
    title: "做饭",
    emoji: "🍳",
    categoryId: 1,
    delta: 8,
    description: "下厨照顾今天的胃，也照顾今天的心情。",
    sortOrder: 1,
    isActive: true,
  },
  {
    kind: "positive",
    title: "洗碗",
    emoji: "🧹",
    categoryId: 1,
    delta: 5,
    description: "收尾也很重要，认真到底值得被表扬。",
    sortOrder: 2,
    isActive: true,
  },
  {
    kind: "positive",
    title: "陪梨梨散步",
    emoji: "🚶",
    categoryId: 2,
    delta: 10,
    description: "一起散散步，让今天慢一点、甜一点。",
    sortOrder: 3,
    isActive: true,
  },
  {
    kind: "positive",
    title: "准备小惊喜",
    emoji: "🎁",
    categoryId: 4,
    delta: 20,
    description: "爱意被用心准备的时候，会特别闪闪发光。",
    sortOrder: 4,
    isActive: true,
  },
  {
    kind: "negative",
    title: "熬夜",
    emoji: "🌙",
    categoryId: 3,
    delta: -5,
    description: "身体要先被照顾好，早点睡是长期主义。",
    sortOrder: 5,
    isActive: true,
  },
  {
    kind: "negative",
    title: "忘记倒垃圾",
    emoji: "🗑️",
    categoryId: 1,
    delta: -3,
    description: "小家要一起维护，记得顺手完成收尾。",
    sortOrder: 6,
    isActive: true,
  },
  {
    kind: "negative",
    title: "打游戏太久",
    emoji: "🎮",
    categoryId: 3,
    delta: -8,
    description: "休闲可以有，但也别把时间都交出去。",
    sortOrder: 7,
    isActive: true,
  },
  {
    kind: "negative",
    title: "态度敷衍",
    emoji: "😠",
    categoryId: 2,
    delta: -10,
    description: "好好说话，比赢一时更重要。",
    sortOrder: 8,
    isActive: true,
  },
];

export const DEFAULT_REWARDS: RewardInput[] = [
  {
    title: "一个亲亲",
    emoji: "❤️",
    cost: 30,
    description: "被认真记录之后，也值得认真奖励。",
    accentColor: "#ff9db4",
    sortOrder: 1,
    isActive: true,
  },
  {
    title: "奶茶约会",
    emoji: "🧋",
    cost: 60,
    description: "挑一家想去的小店，认真约会一次。",
    accentColor: "#f2c889",
    sortOrder: 2,
    isActive: true,
  },
  {
    title: "火锅",
    emoji: "🍲",
    cost: 120,
    description: "热乎乎的一餐，适合庆祝所有努力。",
    accentColor: "#ffb58c",
    sortOrder: 3,
    isActive: true,
  },
  {
    title: "电影之夜",
    emoji: "🎬",
    cost: 150,
    description: "把客厅变成你们自己的小影院。",
    accentColor: "#cdb6ff",
    sortOrder: 4,
    isActive: true,
  },
  {
    title: "一日游戏自由",
    emoji: "🎮",
    cost: 200,
    description: "认真努力换来完全放心的放松一天。",
    accentColor: "#97d6bf",
    sortOrder: 5,
    isActive: true,
  },
];

export const DEFAULT_LEVELS: LevelInput[] = [
  {
    name: "小猪仔",
    threshold: 0,
    badgeEmoji: "🐷",
    accentColor: "#f3a5b6",
    sortOrder: 1,
  },
  {
    name: "乖乖猪",
    threshold: 100,
    badgeEmoji: "🌸",
    accentColor: "#f4c77c",
    sortOrder: 2,
  },
  {
    name: "暖心猪",
    threshold: 300,
    badgeEmoji: "☁️",
    accentColor: "#9bc9b1",
    sortOrder: 3,
  },
  {
    name: "超级猪猪",
    threshold: 600,
    badgeEmoji: "👑",
    accentColor: "#ffb28a",
    sortOrder: 4,
  },
  {
    name: "梨梨专属猪猪",
    threshold: 1000,
    badgeEmoji: "💖",
    accentColor: "#ff8ea9",
    sortOrder: 5,
  },
];

export const DEFAULT_QUOTES: QuoteInput[] = [
  {
    content: "梨梨一直都有看到猪猪的努力 ❤️",
    sortOrder: 1,
    isActive: true,
  },
  {
    content: "今天也辛苦啦，认真生活的猪猪最会发光。",
    sortOrder: 2,
    isActive: true,
  },
  {
    content: "保持可爱，也保持努力，慢慢变成更闪亮的自己。",
    sortOrder: 3,
    isActive: true,
  },
  {
    content: "被认真记录的每一点进步，都会在未来开花。",
    sortOrder: 4,
    isActive: true,
  },
];
